version: "3"
services:
  spring-mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    env_file: ./.env
  users-service:
    image: spring-mysql-service
    ports:
      - 8011:8011
    depends_on:
      - spring-mysql
      - redis-cache
    command: sh -c 'sleep 20s && java -jar application.jar'
    links:
      - redis-cache
      - spring-mysql
  redis-cache:
    image: redis
    ports:
      - 6379:6379

